### ISSUE TITLE
If the latex contains Chinese characters, the mathjson will not be parsed correctly

### ISSUE THREAD

**Issue by shenggaowei** [cortex-js/compute-engine#84]
I want to convert latex containing Chinese characters to mathjson, for example "\Delta钢筋=\Delta钢铁+\Delta混凝土", but the parsing result is not properly, is there a relevant configuration item, or is this a bug? 

The test results provided in the demo on the official website

![image](https://github.com/cortex-js/compute-engine/assets/34361947/99128373-c30a-4266-a1df-01520ca8cffe)

**Comment by arnog** [comment]
This is fixed now, but the in order to be considered a single identifier, the sequence of characters must be enclosed in a grouping command, for example `\mathrm{\Delta钢筋}`, otherwise they will get interpreted as an implicit product.

**Comment by shenggaowei** [comment]
> This is fixed now, but the in order to be considered a single identifier, the sequence of characters must be enclosed in a grouping command, for example `\mathrm{\Delta钢筋}`, otherwise they will get interpreted as an implicit product.现在已修复此问题，但为了被视为单个标识符，字符序列必须包含在分组命令中，例如 `\mathrm{\Delta钢筋}` ，否则它们将被解释为隐式乘积。

Why I test the parsing result in the demo is still not correct, is not yet released？
![image](https://github.com/cortex-js/compute-engine/assets/34361947/ce812f13-9c00-4c4f-bfdf-465340df926a)

**Comment by arnog** [comment]
That's correct. It's fixed in the main branch, but I haven't published a release yet. Stand by.

**Comment by shenggaowei** [comment]
Okay, I'll go ahead and package the main branch myself. Thanks to the author for providing such a good library
